"use client";

import type { McpConnection, ProjectKit } from "@/types/vibeforge";
import { SECTION_ORDER, ZIP_FILE_MAP, sectionFilename, sectionTitle } from "@/lib/kit-sections";
import { normalizeProjectWorkspace } from "@/lib/section-workspace";
import { downloadBlob, slugify } from "@/lib/utils";

export function kitToMarkdown(project: ProjectKit) {
  const normalized = normalizeProjectWorkspace(project);
  const body = SECTION_ORDER.map(([key, title]) => {
    const content = normalized.sections[key] ?? "";
    return `# ${title}\n\n${content.trim()}`;
  }).join("\n\n---\n\n");

  return `# ${normalized.name}\n\nGenerated by VibeForge on ${new Date(normalized.createdAt).toLocaleString()}.\n\n${body}\n`;
}

export function downloadMarkdown(project: ProjectKit, sectionKey?: string) {
  const normalized = normalizeProjectWorkspace(project);
  const name = slugify(normalized.name || "vibeforge-project");
  const content = sectionKey
    ? `# ${sectionTitle(sectionKey)}\n\n${normalized.sections[sectionKey] ?? ""}\n`
    : kitToMarkdown(normalized);
  const filename = sectionKey ? sectionFilename(sectionKey) : `${name}-project-kit.md`;
  downloadBlob(filename, new Blob([content], { type: "text/markdown;charset=utf-8" }));
}

export function downloadProjectJson(project: ProjectKit) {
  const normalized = normalizeProjectWorkspace(project);
  const name = slugify(normalized.name || "vibeforge-project");
  downloadBlob(
    `${name}.json`,
    new Blob([JSON.stringify(normalized, null, 2)], { type: "application/json;charset=utf-8" }),
  );
}

export async function downloadZip(project: ProjectKit) {
  const normalized = normalizeProjectWorkspace(project);
  const JSZip = (await import("jszip")).default;
  const zip = new JSZip();
  Object.entries(ZIP_FILE_MAP).forEach(([key, filename]) => {
    zip.file(filename, `# ${sectionTitle(key)}\n\n${normalized.sections[key] ?? ""}\n`);
  });
  zip.file("REPO_MAP.md", `# Repo Map\n\n${normalized.sections["repo-tool-map"] ?? ""}\n`);
  zip.file("project.json", JSON.stringify(normalized, null, 2));
  const blob = await zip.generateAsync({ type: "blob" });
  downloadBlob(`${slugify(normalized.name)}-kit.zip`, blob);
}

export function downloadMcpJson(connections: McpConnection[]) {
  downloadBlob(
    "vibeforge-mcp-connections.json",
    new Blob([JSON.stringify(connections, null, 2)], {
      type: "application/json;charset=utf-8",
    }),
  );
}
