import type { McpConnection, ProjectKit } from "@/types/vibeforge";
import {
  AGENT_EXPORT_PACKS,
  type AgentExportPackId,
  SECTION_ORDER,
  ZIP_FILE_MAP,
  sectionTitle,
} from "@/lib/kit-sections";
import { slugify } from "@/lib/utils";

export const SENSITIVE_EXPORT_MARKERS = [
  "apiKey",
  "ciphertext",
  "providerKey",
  "sk-test-sensitive",
  "sk-or-v1-",
  "api_key_ciphertext",
];

export function kitToMarkdown(project: ProjectKit) {
  const body = SECTION_ORDER.map(([key, title]) => {
    const content = project.sections[key] ?? "";
    return `# ${title}\n\n${content.trim()}`;
  }).join("\n\n---\n\n");

  return `# ${project.name}\n\nGenerated by VibeForge on ${new Date(project.createdAt).toLocaleString()}.\n\n${body}\n`;
}

export function projectSlug(project: ProjectKit) {
  return slugify(project.name || "vibeforge-project") || "vibeforge-project";
}

const SENSITIVE_EXPORT_KEYS = new Set([
  "apikey",
  "ciphertext",
  "providersecret",
  "fallbacksecret",
  "provider_secret",
  "fallback_secret",
  "api_key_ciphertext",
  "api_key_iv",
  "api_key_tag",
  "api_key",
  "secret",
  "token",
  "password",
  "credential",
  "api-key"
]);

function sanitizeObject(obj: unknown): unknown {
  if (!obj || typeof obj !== "object") return obj;
  if (Array.isArray(obj)) return obj.map(sanitizeObject);
  
  const sanitized: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj as Record<string, unknown>)) {
    const normalizedKey = key.toLowerCase().replace(/[^a-z0-9_-]/g, "");
    if (SENSITIVE_EXPORT_KEYS.has(normalizedKey)) {
      continue;
    }
    sanitized[key] = sanitizeObject(value);
  }
  return sanitized;
}

export function projectToExportJson(project: ProjectKit): Record<string, unknown> {
  const { generation, ...rest } = project;
  const exported = {
    ...rest,
    generation: generation
      ? {
          mode: generation.mode,
          source: generation.source,
          generatedAt: generation.generatedAt,
        }
      : undefined,
  };
  return sanitizeObject(exported) as Record<string, unknown>;
}

export function projectJsonString(project: ProjectKit) {
  return JSON.stringify(projectToExportJson(project), null, 2);
}

export function zipFileEntries(project: ProjectKit): Record<string, string> {
  const files: Record<string, string> = {};
  Object.entries(ZIP_FILE_MAP).forEach(([key, filename]) => {
    files[filename] = `# ${sectionTitle(key)}\n\n${project.sections[key] ?? ""}\n`;
  });
  files["REPO_MAP.md"] = `# Repo Map\n\n${project.sections["repo-tool-map"] ?? ""}\n`;
  files["project.json"] = projectJsonString(project);
  return files;
}

export function agentPackFileEntries(project: ProjectKit, packId: AgentExportPackId): Record<string, string> {
  const pack = AGENT_EXPORT_PACKS.find((item) => item.id === packId);
  if (!pack) throw new Error("Unknown export pack.");

  const files: Record<string, string> = {};
  pack.files.forEach((filename) => {
    files[filename] = buildAgentPackFile(project, filename);
  });
  files["project.json"] = projectJsonString(project);
  return files;
}

export function mcpJsonString(connections: McpConnection[]) {
  return JSON.stringify(connections, null, 2);
}

export function exportContainsSensitiveMarkers(content: string) {
  return SENSITIVE_EXPORT_MARKERS.some((marker) => content.includes(marker));
}

function buildAgentPackFile(project: ProjectKit, filename: string) {
  const sections = project.sections;
  const recommendations = project.repoRecommendations ?? [];
  const useNowTools = recommendations
    .filter((item) => item.lane === "use-now")
    .map((item) => item.tool.name)
    .join(", ");
  const nextActions = [
    ...(project.readinessScore?.nextActions?.length
      ? project.readinessScore.nextActions
      : [
          "Review PROJECT_BRIEF.md and TASKS.md.",
          "Pick one first milestone and implement the smallest working path.",
          "Verify Markdown, JSON, ZIP, and agent-pack exports still work.",
        ]),
    "Open TASKS.md and complete the first milestone before adding use-later tools.",
    "Run lint, build, and the manual export checklist after implementation changes.",
  ];
  const projectBrief = [
    sections["product-strategy"] ?? "",
    "",
    "## Build Context",
    `- App type: ${project.input.appType}`,
    `- Timeline: ${project.input.timeline}`,
    `- Skill level: ${project.input.skillLevel}`,
    `- Budget sensitivity: ${project.input.budgetSensitivity}`,
    `- Use-now tools: ${useNowTools || "None selected"}`,
  ].join("\n");

  const fileMap: Record<string, string> = {
    "AGENTS.md": sections["coding-agent-rules"] ?? "",
    ".clinerules": clineRules(project),
    ".cursorrules": cursorRules(project),
    "CLAUDE.md": claudeRules(project),
    "PROJECT_BRIEF.md": projectBrief,
    "PRODUCT_REQUIREMENTS.md": sections["product-strategy"] ?? projectBrief,
    "MVP_SCOPE.md": sections["mvp-scope"] ?? "",
    "ARCHITECTURE.md": sections["stack-recommendation"] ?? "",
    "DATABASE_SCHEMA.md": sections["database-schema"] ?? "",
    "API_SPEC.md": sections["api-specification"] ?? "",
    "UI_SCREENS.md": sections["ui-screens"] ?? "",
    "USER_FLOWS.md": sections["user-flows"] ?? "",
    "AI_HANDOFF.md": sections["ai-handoff"] ?? aiHandoffFile(project, projectBrief),
    "TASKS.md": sections["task-plan"] ?? "",
    "IMPLEMENTATION_PHASES.md": sections["implementation-phases"] ?? sections["feature-roadmap"] ?? "",
    "TOOLS.md": buildToolsSummary(project),
    "REPO_REFERENCES.md": sections["repo-tool-map"] ?? "",
    "TEST_PLAN.md": sections["test-plan"] ?? "",
    "DEPLOYMENT_PLAN.md": sections["deployment-plan"] ?? "",
    "SECURITY_CHECKLIST.md": sections["security-checklist"] ?? "",
    "NEXT_ACTIONS.md": `# Next Actions\n\n${nextActions.map((item) => `- ${item}`).join("\n")}\n`,
    "VIBE_CODING_PROMPTS.md": sections["codex-cline-prompts"] ?? "",
  };
  return `# ${filename}\n\n${fileMap[filename]?.trim() ?? ""}\n`;
}

function aiHandoffFile(project: ProjectKit, projectBrief: string) {
  return [
    "## Purpose",
    "Use this as the single upload brief for an AI coding agent. It tells the agent what to read, what to build first, what to avoid, and how to verify the work.",
    "",
    "## Project Brief",
    projectBrief,
    "",
    "## Upload These Files Together",
    "1. AI_HANDOFF.md",
    "2. PRODUCT_REQUIREMENTS.md",
    "3. MVP_SCOPE.md",
    "4. ARCHITECTURE.md",
    "5. API_SPEC.md",
    "6. TASKS.md",
    "7. IMPLEMENTATION_PHASES.md",
    "8. REPO_REFERENCES.md",
    "9. SECURITY_CHECKLIST.md",
    "10. TEST_PLAN.md",
    "11. VIBE_CODING_PROMPTS.md",
    "",
    "## Primary Agent Prompt",
    "```text",
    "Read AI_HANDOFF.md, PRODUCT_REQUIREMENTS.md, MVP_SCOPE.md, ARCHITECTURE.md, API_SPEC.md, TASKS.md, IMPLEMENTATION_PHASES.md, REPO_REFERENCES.md, SECURITY_CHECKLIST.md, and TEST_PLAN.md before editing. Implement only the next task from TASKS.md. Preserve local-first/demo behavior. Do not hardcode secrets. Do not clone external repositories automatically. Treat repo URLs as reference-only. Run the listed test command and report changed files, checks run, and remaining risks.",
    "```",
    "",
    "## Definition Of Done",
    "- The selected task satisfies its acceptance criteria.",
    "- The listed test command passes or the blocker is explained with root cause.",
    "- Demo/local-first behavior still works.",
    "- Exports still work.",
    "- No secrets, external repo code, or unrelated rewrites are introduced.",
  ].join("\n");
}

function clineRules(project: ProjectKit) {
  return [
    "Use the VibeForge kit files as the source of truth.",
    "Work one small task at a time from TASKS.md.",
    "Ask before adding paid services, background workers, or repository cloning.",
    "Preserve Markdown, JSON, and ZIP exports.",
    `App type: ${project.input.appType}. Timeline: ${project.input.timeline}.`,
  ].join("\n");
}

function cursorRules(project: ProjectKit) {
  return [
    "Prefer small typed components and local project conventions.",
    "Keep the root route as the usable builder.",
    "Do not require API keys for the core flow.",
    "Treat reference-only repos as architecture references, not source code.",
    `Primary output: ${project.input.desiredOutput || "structured implementation artifacts"}.`,
  ].join("\n");
}

function claudeRules(project: ProjectKit) {
  return [
    "# Claude Code Instructions",
    "",
    "Read PROJECT_BRIEF.md and TASKS.md before editing.",
    "Preserve local-first fallback behavior and export formats.",
    "Do not auto-clone external repositories or execute user-supplied code.",
    "Report changed files and checks run.",
    "",
    `Project: ${project.name}`,
  ].join("\n");
}

function buildToolsSummary(project: ProjectKit) {
  const recs = project.repoRecommendations ?? [];
  if (recs.length === 0) return project.sections["repo-tool-map"] ?? "";

  const useNow = recs.filter((r) => r.lane === "use-now");
  const useLater = recs.filter((r) => r.lane === "use-later");
  const refOnly = recs.filter((r) => r.lane === "reference-only");

  const lines: string[] = [
    "## Recommended Tools",
    "",
    `**${recs.length} tools** evaluated - ${useNow.length} for MVP, ${useLater.length} for later, ${refOnly.length} reference-only.`,
    "",
  ];

  if (useNow.length) {
    lines.push("### Use Now (MVP)");
    useNow.forEach((r) => lines.push(`- **${r.tool.name}** - ${r.tool.useCase}`));
    lines.push("");
  }
  if (useLater.length) {
    lines.push("### Use Later (Post-MVP)");
    useLater.forEach((r) => lines.push(`- **${r.tool.name}** - ${r.tool.useCase}`));
    lines.push("");
  }
  if (refOnly.length) {
    lines.push("### Reference Only");
    refOnly.forEach((r) => lines.push(`- **${r.tool.name}** - ${r.tool.useCase}`));
    lines.push("");
  }

  lines.push("---");
  lines.push("See REPO_REFERENCES.md for full URLs and no-clone policy.");
  return lines.join("\n");
}
